name: Documentation Linter

on:
  push:
    paths: 
      - '**.md'
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v3
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with: 
          config: '.markdownlint.json'
          args: '**/*.md'
          ignore: './README.md ./docs/index.md'